---
language: scala
scala:
- 2.10.1
jdk:
- openjdk7
script: mvn install
after_success: mvn deploy
env:
  global:
  - secure: ! 'WdakfA0d2FfiqUgWVHQMeqjJaew4fXkPAaUjUedSQW2yRkzHFelYcLXmNdkm

      FT+3VvvZxhGFp23s+HVP17pxnoMSRv31gR1uZB2t2U4Bi9/iZmII3vx9ZS9i

      abnxGElVC/zhkP6iezlQpPpdzg35i9XB7BShZBqK2i9+9wRTjzY='
